title: "Brendan Miller | Personal site"
email: "bmille79@jhu.edu"
description: Personal website of Dr. Brendan Miller
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://brendan.miller" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:year/:month/:day/:title:output_ext"
# Build settings
markdown: kramdown
theme: minima

# General Settings
logo_url: "/assets/img/logo/logo.png"
banner_url: "/assets/img/banner-small.jpg"

company_name: Brendan Miller
company_url: "https://brendan.miller"
lab_url: "https://github.com/bmill3r"
twitter_url: "https://twitter.com/bf_miller_"
# instagram_url: ""
youtube_url: "https://scholar.google.com/citations?user=BP7VBw0AAAAJ&hl=en"
linkedin_url: "https://linkedin.com/in/brendan-f-miller"


# define folders with pages/files to interate over using `liquid` syntax in code
collections:
  pubs:
    output: true
  home_one_services:
    output: true